// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using LazyTravel.Models.EfModels;

namespace LazyTravel.Models;

public partial class LazyTravelContext : DbContext
{
    public LazyTravelContext(DbContextOptions<LazyTravelContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<GroupMember> GroupMembers { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<TravelGroup> TravelGroups { get; set; }

    public virtual DbSet<ReportTargetTypeLookup> ReportTargetTypeLookups { get; set; }

    public virtual DbSet<ReportReasonCategoryLookup> ReportReasonCategoryLookups { get; set; }

    public virtual DbSet<ReportStatusLookup> ReportStatusLookups { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId);
        });

        // 這個 Context 只需要 Employee.Name(隨機挑審核人員用),不需要 Employee 導覽屬性牽出來的
        // EmployeeRole/AdminAuditLog/AdminLog,那些是 LazyTravelDBContext(員工/RBAC)的範圍,
        // 這裡沒設定它們的主鍵,不排除的話 EF 建模時會炸掉
        modelBuilder.Ignore<EmployeeRole>();
        modelBuilder.Ignore<AdminAuditLog>();
        modelBuilder.Ignore<AdminLog>();
        modelBuilder.Ignore<Role>();
        modelBuilder.Ignore<RolePermission>();
        modelBuilder.Ignore<Permission>();

        modelBuilder.Entity<GroupMember>(entity =>
        {
            entity.HasKey(e => e.GroupMemberId).HasName("PK__GroupMem__344812B27A4F4AA7");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.JoinedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.MemberRole).HasDefaultValue((byte)0);

            entity.HasOne(d => d.Group).WithMany(p => p.GroupMembers).OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Member).WithMany(p => p.GroupMemberMembers).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK__Members__0CF04B386BB05866");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue((byte)1);
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            // Reports 對 Members 有兩條各自獨立的外鍵(誰檢舉的、被檢舉的是誰),
            // 兩條都指向同一張表,EF Core 沒辦法自己猜,必須各自明講要用哪個外鍵、不要牽連對方
            entity.HasOne(d => d.Reporter)
                .WithMany()
                .HasForeignKey(d => d.ReporterId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.ReportedMember)
                .WithMany()
                .HasForeignKey(d => d.ReportedMemberId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TravelGroup>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__TravelGr__149AF30A9EC21FB3");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CurrentPeople).HasDefaultValue(1);
            entity.Property(e => e.GroupStatus).HasDefaultValue((byte)0);
            entity.Property(e => e.IsPublic).HasDefaultValue(true);
            entity.Property(e => e.JoinRule).HasDefaultValue((byte)1);
            entity.Property(e => e.MaxPeople).HasDefaultValue(10);
            entity.Property(e => e.MinPeople).HasDefaultValue(2);
            entity.Property(e => e.ReviewStatus)
                .HasDefaultValue("正常")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TravelGroups_ReviewStatus");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.OwnerMember).WithMany(p => p.TravelGroups).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ReportTargetTypeLookup>(entity =>
        {
            entity.HasKey(e => e.TypeId);
            entity.ToTable("ReportTargetTypes");
        });

        modelBuilder.Entity<ReportReasonCategoryLookup>(entity =>
        {
            entity.HasKey(e => e.CategoryId);
            entity.ToTable("ReportReasonCategories");
        });

        modelBuilder.Entity<ReportStatusLookup>(entity =>
        {
            entity.HasKey(e => e.StatusId);
            entity.ToTable("ReportStatuses");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}