// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models;

[Index("Email", Name = "UQ_Members_Email", IsUnique = true)]
public partial class Member
{
    [Key]
    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(255)]
    public string PasswordHash { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(255)]
    public string InstagramUrl { get; set; }

    [StringLength(255)]
    public string FacebookUrl { get; set; }

    [StringLength(50)]
    public string LineId { get; set; }

    public bool IsPrivateAccount { get; set; }

    public byte ContactBookVisibility { get; set; }

    public bool IsEmailConfirmed { get; set; }

    public string AvatarUrl { get; set; }

    public DateOnly? BirthDate { get; set; }

    public byte Gender { get; set; }

    [StringLength(50)]
    public string Occupation { get; set; }

    [Column("MBTI")]
    [StringLength(4)]
    [Unicode(false)]
    public string Mbti { get; set; }

    [StringLength(500)]
    public string Bio { get; set; }

    public byte Status { get; set; }

    public byte Role { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLoginAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastLoginIp { get; set; }

    public int FailedLoginCount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LockoutEndDate { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<GroupMember> GroupMemberMembers { get; set; } = new List<GroupMember>();

    [InverseProperty("RemovedByMember")]
    public virtual ICollection<GroupMember> GroupMemberRemovedByMembers { get; set; } = new List<GroupMember>();

    [InverseProperty("OwnerMember")]
    public virtual ICollection<TravelGroup> TravelGroups { get; set; } = new List<TravelGroup>();
}