// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models;

public partial class TravelGroup
{
    [Key]
    [Column("GroupID")]
    public int GroupId { get; set; }

    [Column("OwnerMemberID")]
    public int OwnerMemberId { get; set; }

    [Required]
    [StringLength(100)]
    public string GroupTitle { get; set; }

    [StringLength(1000)]
    public string Description { get; set; }

    public int MinPeople { get; set; }

    public int MaxPeople { get; set; }

    public int CurrentPeople { get; set; }

    public byte JoinRule { get; set; }

    public byte GroupStatus { get; set; }

    public bool IsPublic { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    public bool IsDelete { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    [InverseProperty("Group")]
    public virtual ICollection<JoinRequest> JoinRequests { get; set; } = new List<JoinRequest>();

    [ForeignKey("OwnerMemberId")]
    [InverseProperty("TravelGroups")]
    public virtual Member OwnerMember { get; set; }

    public string ReviewStatus { get; set; } = null!;
    public string? Country { get; set; }
    public string? Region { get; set; }
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }

}