// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

[PrimaryKey("AdminId", "PermissionCode")]
public partial class AdminPermission
{
    [Key]
    [Column("AdminID")]
    public int AdminId { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string PermissionCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("AdminId")]
    [InverseProperty("AdminPermissions")]
    public virtual Member Admin { get; set; }
}