// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Category
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public byte ModuleType { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ForumPost> ForumPosts { get; set; } = new List<ForumPost>();
}