// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ExpenseSplit
{
    public int SplitId { get; set; }

    public int ExpenseId { get; set; }

    public int MemberId { get; set; }

    public decimal OweAmount { get; set; }

    public bool IsPaid { get; set; }

    public virtual Expense Expense { get; set; }

    public virtual Member Member { get; set; }
}