// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Follow
{
    public int FollowId { get; set; }

    public int FollowerId { get; set; }

    public int FolloweeId { get; set; }

    public byte Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Member Followee { get; set; }

    public virtual Member Follower { get; set; }
}