// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ForumPost
{
    public int ForumPostId { get; set; }

    public int MemberId { get; set; }

    public int CategoryId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public bool IsPinned { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDelete { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ForumComment> ForumComments { get; set; } = new List<ForumComment>();

    public virtual ICollection<ForumImage> ForumImages { get; set; } = new List<ForumImage>();

    public virtual ICollection<ForumInteract> ForumInteracts { get; set; } = new List<ForumInteract>();

    public virtual Member Member { get; set; }
}