// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ForumInteract
{
    public int ForumPostId { get; set; }

    public int MemberId { get; set; }

    public byte ActionType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ForumPost ForumPost { get; set; }

    public virtual Member Member { get; set; }
}