// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ForumImage
{
    public int ImageId { get; set; }

    public int ForumPostId { get; set; }

    public string ImageUrl { get; set; }

    public int SortOrder { get; set; }

    public virtual ForumPost ForumPost { get; set; }
}