// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class GroupMember
{
    public int GroupMemberId { get; set; }

    public int GroupId { get; set; }

    public int MemberId { get; set; }

    public byte MemberRole { get; set; }

    public DateTime JoinedAt { get; set; }

    public DateTime? LeftAt { get; set; }

    public bool IsRemoved { get; set; }

    public int? RemovedByMemberId { get; set; }

    public DateTime? RemovedAt { get; set; }

    public string RemoveReason { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TravelGroup Group { get; set; }

    public virtual Member Member { get; set; }

    public virtual Member RemovedByMember { get; set; }
}