// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// 🌟 手動調整：MediaType 屬性型別從反向工程原本產生的 byte 改成 VlogMediaType enum
// （型別定義在 VlogPostEnums.cs）。資料庫欄位還是 tinyint，用 HasConversion<byte>() 轉換
// （設定在 LazyTravelDBContext.OnModelCreating）。日後重新反向工程記得改回來。
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ItineraryNode
{
    public int NodeId { get; set; }

    public int PostId { get; set; }

    public int DayNumber { get; set; }

    public string LocationName { get; set; }

    public TimeOnly? ArrivalTime { get; set; }

    public int? StayTime { get; set; }

    public TimeOnly? DepartureTime { get; set; }

    public string MediaUrl { get; set; }

    public VlogMediaType MediaType { get; set; }

    public string Description { get; set; }

    public string Remarks { get; set; }

    public virtual VlogPost Post { get; set; }
}