// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ItineraryNode
{
    public int NodeId { get; set; }

    public int PostId { get; set; }

    public int DayNumber { get; set; }

    public string LocationName { get; set; }

    public TimeOnly? ArrivalTime { get; set; }

    public int? StayTime { get; set; }

    public TimeOnly? DepartureTime { get; set; }

    public string MediaUrl { get; set; }

    public VlogMediaType MediaType { get; set; }

    public string Description { get; set; }

    public string Remarks { get; set; }

    public virtual VlogPost Post { get; set; }
}