// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class JoinRequest
{
    public int RequestId { get; set; }

    public int GroupId { get; set; }

    public int MemberId { get; set; }

    public string Message { get; set; }

    public byte RequestStatus { get; set; }

    public int? ReviewedByMemberId { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TravelGroup Group { get; set; }

    public virtual Member Member { get; set; }

    public virtual Member ReviewedByMember { get; set; }
}