// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class MemberTravelDNA
{
    public int MemberId { get; set; }

    public byte DimensionId { get; set; }

    public byte Score { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual TravelDNADimension Dimension { get; set; }

    public virtual Member Member { get; set; }
}
