// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class MemberToken
{
    [Key]
    [Column("TokenID")]
    public int TokenId { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(50)]
    public string LoginProvider { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    public string Value { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExpiryTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("MemberTokens")]
    public virtual Member Member { get; set; }
}