// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int MemberId { get; set; }

    public byte NotificationCategory { get; set; }

    public byte? TargetType { get; set; }

    public int? RelatedId { get; set; }

    public string Content { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member Member { get; set; }
}