// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// 🌟 手動調整：ActionType 屬性型別從反向工程原本產生的 byte 改成 PostInteractionType enum
// （型別定義在 PostInteractionEnums.cs）。資料庫欄位是 tinyint，用 HasConversion<byte>() 轉換
// （設定在 LazyTravelDBContext.OnModelCreating）。日後重新反向工程記得改回來。
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class PostInteraction
{
    public int PostId { get; set; }

    public int MemberId { get; set; }

    public PostInteractionType ActionType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member Member { get; set; }

    public virtual VlogPost Post { get; set; }
}