// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// 🌟 手動改名：EF Core Power Tools 反向工程原本會把這個類別叫 ReportTargetType，
// 跟 LazyTravel.Shared.Models.Report.cs 裡手寫的 enum ReportTargetType 撞名（CS0104）。
// 改回 ReportTargetTypeLookup（連同 DbSet 屬性名稱 ReportTargetTypeLookups）是為了對齊
// 重構前就存在的命名，日後如果重新反向工程，記得把類別名稱和 DbSet 屬性名稱都改回這個樣子。
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ReportTargetTypeLookup
{
    public byte TypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}
