// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Report
{
    public int ReportId { get; set; }

    public int ReporterId { get; set; }

    public int? ReportedMemberId { get; set; }

    public byte ReportType { get; set; }

    public int? TargetId { get; set; }

    public string Reason { get; set; }

    public byte ReportStatus { get; set; }

    public string AdminNotes { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte ReasonCategory { get; set; }

    public bool IsMalicious { get; set; }

    public string TargetTitle { get; set; }

    public string Description { get; set; }

    public string EvidenceUrl { get; set; }

    public string TargetSnapshot { get; set; }

    public virtual ReportReasonCategoryLookup ReasonCategoryNavigation { get; set; }

    public virtual ReportStatusLookup ReportStatusNavigation { get; set; }

    public virtual ReportTargetTypeLookup ReportTypeNavigation { get; set; }

    public virtual Member ReportedMember { get; set; }

    public virtual Member Reporter { get; set; }
}