// <auto-generated> This file has been generated via `dotnet ef dbcontext scaffold` (table: ReportTargetTypes). </auto-generated>
namespace LazyTravel.Models.EfModels;

public partial class ReportTargetTypeLookup
{
    public byte TypeId { get; set; }

    public string TypeName { get; set; } = null!;
}
