// <auto-generated> This file has been generated via `dotnet ef dbcontext scaffold` (table: ReportStatuses). </auto-generated>
namespace LazyTravel.Models.EfModels;

public partial class ReportStatusLookup
{
    public byte StatusId { get; set; }

    public string StatusName { get; set; } = null!;
}
