// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

[Index("RoleCode", Name = "UQ_Roles_RoleCode", IsUnique = true)]
public partial class Role
{
    [Key]
    [Column("RoleID")]
    public int RoleId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleCode { get; set; }

    [Required]
    [StringLength(50)]
    public string RoleName { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();

    [InverseProperty("Role")]
    public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; } = new List<EmployeeRole>();

    // 透過 RolePermissions 中介表直達權限(EF Core skip navigation),
    // 讓 EmployeeService 可以直接 Include(r => r.Permissions) / role.Permissions.Clear()。
    // 對應設定在 LazyTravelDBContext 的 UsingEntity<RolePermission>。
    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}
