// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Role
{
    public int RoleId { get; set; }

    public string RoleCode { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; } = new List<EmployeeRole>();

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}