// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class SubscriptionPlan
{
    public int PlanId { get; set; }

    public string PlanName { get; set; }

    public decimal Price { get; set; }

    public int DurationDays { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<MemberSubscription> MemberSubscriptions { get; set; } = new List<MemberSubscription>();
}