// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelDnaDimension
{
    public byte DimensionId { get; set; }

    public string DimensionName { get; set; }

    public string LeftLabel { get; set; }

    public string RightLabel { get; set; }

    public virtual ICollection<MemberTravelDna> MemberTravelDnas { get; set; } = new List<MemberTravelDna>();

    public virtual ICollection<TravelDnaOption> TravelDnaOptions { get; set; } = new List<TravelDnaOption>();
}
