// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelDNAOption
{
    public int OptionId { get; set; }

    public byte DimensionId { get; set; }

    public string OptionName { get; set; }

    public string Description { get; set; }

    public byte MinScore { get; set; }

    public byte MaxScore { get; set; }

    public virtual TravelDNADimension Dimension { get; set; }
}
