// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelGroupBudget
{
    public int BudgetId { get; set; }

    public int GroupId { get; set; }

    public byte BudgetCategory { get; set; }

    public string BudgetName { get; set; }

    public decimal? Amount { get; set; }

    public string CurrencyCode { get; set; }

    public bool IsRequired { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual TravelGroup Group { get; set; }
}