// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// 🌟 手動調整：ReviewStatus 屬性型別從反向工程原本產生的 byte 改成 TravelGroupReviewStatus enum
// （型別定義在 TravelGroupEnums.cs）。資料庫欄位是 tinyint，用 HasConversion<byte>() 轉換
// （設定在 LazyTravelDBContext.OnModelCreating）。日後重新反向工程記得改回來。
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelGroup
{
    public int GroupId { get; set; }

    public int OwnerMemberId { get; set; }

    public string GroupTitle { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int MinPeople { get; set; }

    public int MaxPeople { get; set; }

    public int CurrentPeople { get; set; }

    public byte JoinRule { get; set; }

    public byte GroupStatus { get; set; }

    public bool IsPublic { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDelete { get; set; }

    public TravelGroupReviewStatus ReviewStatus { get; set; }

    public string Country { get; set; }

    public string Region { get; set; }

    // 🌟 V4 規格書新增欄位（住宿偏好相關），資料庫已用 add_travelgroups_columns_v4.sql 補上。
    public string AccommType { get; set; }

    public bool? CanShareRoom { get; set; }

    public string AccommNote { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<JoinRequest> JoinRequests { get; set; } = new List<JoinRequest>();

    public virtual Member OwnerMember { get; set; }

    public virtual ICollection<TravelGroupBudget> TravelGroupBudgets { get; set; } = new List<TravelGroupBudget>();

    public virtual ICollection<TravelGroupImage> TravelGroupImages { get; set; } = new List<TravelGroupImage>();

    public virtual ICollection<TravelGroupItineraryItem> TravelGroupItineraryItems { get; set; } = new List<TravelGroupItineraryItem>();

    public virtual ICollection<TravelGroupsLog> TravelGroupsLogs { get; set; } = new List<TravelGroupsLog>();

    public virtual ICollection<TravelGroupTag> TravelGroupTags { get; set; } = new List<TravelGroupTag>();
}