// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelDNADimension
{
    public byte DimensionId { get; set; }

    public string DimensionName { get; set; }

    public string LeftLabel { get; set; }

    public string RightLabel { get; set; }

    public virtual ICollection<MemberTravelDNA> MemberTravelDnas { get; set; } = new List<MemberTravelDNA>();

    public virtual ICollection<TravelDNAOption> TravelDnaOptions { get; set; } = new List<TravelDNAOption>();
}