// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;
 
public partial class Member : IdentityUser<int>
{
    public virtual ICollection<TravelGroupTag> TravelGroupTags { get; set; } = new List<TravelGroupTag>();
    public int GroupId { get; set; }

    public int OwnerMemberId { get; set; }

    public string GroupTitle { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int MinPeople { get; set; }

    public int MaxPeople { get; set; }

    public int CurrentPeople { get; set; }

    public byte JoinRule { get; set; }

    public byte GroupStatus { get; set; }

    public bool IsPublic { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDelete { get; set; }

    public TravelGroupReviewStatus ReviewStatus { get; set; }

    public string Country { get; set; }

    public string Region { get; set; }

    public string AccommType { get; set; }

    public bool? CanShareRoom { get; set; }

    public string AccommNote { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<JoinRequest> JoinRequests { get; set; } = new List<JoinRequest>();

    public virtual Member OwnerMember { get; set; }

    public virtual ICollection<TravelGroupBudget> TravelGroupBudgets { get; set; } = new List<TravelGroupBudget>();

    public virtual ICollection<TravelGroupImage> TravelGroupImages { get; set; } = new List<TravelGroupImage>();

    public virtual ICollection<TravelGroupItineraryItem> TravelGroupItineraryItems { get; set; } = new List<TravelGroupItineraryItem>();

