// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// 🌟 手動調整：MediaType / Status / TravelPeople 這三個屬性型別從反向工程原本產生的
// byte / byte / string 改成下面對應的 enum（型別定義搬到 VlogPostEnums.cs，不會被反向工程蓋掉，
// 但這三行屬性型別本身還是在這個會被覆蓋的檔案裡，日後重新反向工程記得改回來）。
// 資料庫欄位型別：MediaType/Status 還是 tinyint（HasConversion<byte>()），
// TravelPeople 現在是 nvarchar(50)（HasConversion<string>()）——都在 LazyTravelDBContext.OnModelCreating 設定。
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class VlogPost
{
    public int PostId { get; set; }

    public int MemberId { get; set; }

    public string Title { get; set; }

    public string MediaUrl { get; set; }

    public VlogMediaType MediaType { get; set; }

    public string Content { get; set; }

    public string Destination { get; set; }

    public int TravelDays { get; set; }

    public VlogPostStatus Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? TravelDate { get; set; }

    public TravelGroupSize TravelPeople { get; set; }

    public bool IsDelete { get; set; }

    public virtual ICollection<ItineraryNode> ItineraryNodes { get; set; } = new List<ItineraryNode>();

    public virtual Member Member { get; set; }

    public virtual ICollection<PostInteraction> PostInteractions { get; set; } = new List<PostInteraction>();

    public virtual ICollection<VlogPostImage> VlogPostImages { get; set; } = new List<VlogPostImage>();

    public virtual ICollection<VlogPostTag> VlogPostTags { get; set; } = new List<VlogPostTag>();
}