
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generat
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class VlogPostTag
{
    public int TagId { get; set; }

    public int PostId { get; set; }

    public string TagName { get; set; }

    public string TagCategory { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDelete { get; set; }

    public virtual VlogPost Post { get; set; }
}
