// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class AdminAuditLog
{
    public long LogId { get; set; }

    public int EmployeeId { get; set; }

    public string Action { get; set; }

    public string TargetResource { get; set; }

    public string TargetId { get; set; }

    public string Ipaddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Description { get; set; }

    public virtual Employee Employee { get; set; }
}