// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class AdminAuditLog
{
    [Key]
    [Column("LogID")]
    public long LogId { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Action { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string TargetResource { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TargetId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string IPAddress { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("AdminAuditLogs")]
    public virtual Employee Employee { get; set; }
}
