// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class AdminLog
{
    [Key]
    [Column("LogID")]
    public int LogId { get; set; }

    [Column("AdminID")]
    public int AdminId { get; set; }

    [Required]
    [StringLength(100)]
    public string Action { get; set; }

    [Required]
    [StringLength(50)]
    public string TargetTable { get; set; }

    [Column("TargetID")]
    public int? TargetId { get; set; }

    [StringLength(300)]
    public string Description { get; set; }

    [Column("IPAddress")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ipaddress { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("AdminId")]
    [InverseProperty("AdminLogs")]
    public virtual Member Admin { get; set; }
}