// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Block
{
    public int BlockerId { get; set; }

    public int BlockedId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member Blocked { get; set; }

    public virtual Member Blocker { get; set; }
}