// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class EmployeeRole
{
    public int EmployeeId { get; set; }

    public int RoleId { get; set; }

    public DateTime GrantedAt { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Role Role { get; set; }
}