// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class EmployeeRole
{
    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Column("RoleID")]
    public int RoleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime GrantedAt { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeRoles")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("EmployeeRoles")]
    public virtual Role Role { get; set; }
}
