// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class ExternalLogin
{
    [Key]
    [Column("LoginID")]
    public int LoginId { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(50)]
    public string LoginProvider { get; set; }

    [Required]
    [StringLength(255)]
    public string ProviderKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("ExternalLogins")]
    public virtual Member Member { get; set; }
}