// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class ForumComment
{
    [Key]
    [Column("CommentID")]
    public int CommentId { get; set; }

    [Column("ForumPostID")]
    public int ForumPostId { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(500)]
    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public bool IsDelete { get; set; }

    [ForeignKey("ForumPostId")]
    [InverseProperty("ForumComments")]
    public virtual ForumPost ForumPost { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("ForumComments")]
    public virtual Member Member { get; set; }
}