// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class FriendRequest
{
    public int RequestId { get; set; }

    public int RequesterId { get; set; }

    public int ReceiverId { get; set; }

    public string Message { get; set; }

    public byte RequestStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public virtual Member Receiver { get; set; }

    public virtual Member Requester { get; set; }
}