// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class Friendship
{
    [Key]
    [Column("FriendshipID")]
    public int FriendshipId { get; set; }

    [Column("MemberID1")]
    public int MemberId1 { get; set; }

    [Column("MemberID2")]
    public int MemberId2 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("MemberId1")]
    [InverseProperty("FriendshipMemberId1Navigations")]
    public virtual Member MemberId1Navigation { get; set; }

    [ForeignKey("MemberId2")]
    [InverseProperty("FriendshipMemberId2Navigations")]
    public virtual Member MemberId2Navigation { get; set; }
}