// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Friendship
{
    public int FriendshipId { get; set; }

    public int MemberId1 { get; set; }

    public int MemberId2 { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member MemberId1Navigation { get; set; }

    public virtual Member MemberId2Navigation { get; set; }
}