// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class ItineraryNode
{
    [Key]
    [Column("NodeID")]
    public int NodeId { get; set; }

    [Column("PostID")]
    public int PostId { get; set; }

    public int DayNumber { get; set; }

    [Required]
    [StringLength(100)]
    public string LocationName { get; set; }

    public TimeOnly? ArrivalTime { get; set; }

    [StringLength(50)]
    public string StayTime { get; set; }

    public TimeOnly? DepartureTime { get; set; }

    [StringLength(500)]
    public string MediaUrl { get; set; }

    public byte MediaType { get; set; }

    public string Description { get; set; }

    public string Remarks { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("ItineraryNodes")]
    public virtual VlogPost Post { get; set; }
}