// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class JoinRequest
{
    [Key]
    [Column("RequestID")]
    public int RequestId { get; set; }

    [Column("GroupID")]
    public int GroupId { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    [StringLength(500)]
    public string Message { get; set; }

    public byte RequestStatus { get; set; }

    [Column("ReviewedByMemberID")]
    public int? ReviewedByMemberId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReviewedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("GroupId")]
    [InverseProperty("JoinRequests")]
    public virtual TravelGroup Group { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("JoinRequestMembers")]
    public virtual Member Member { get; set; }

    [ForeignKey("ReviewedByMemberId")]
    [InverseProperty("JoinRequestReviewedByMembers")]
    public virtual Member ReviewedByMember { get; set; }
}