// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class LazyTravelDBContext : DbContext
{
    public LazyTravelDBContext(DbContextOptions<LazyTravelDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminAuditLog> AdminAuditLogs { get; set; }

    public virtual DbSet<AdminLog> AdminLogs { get; set; }

    public virtual DbSet<AdminPermission> AdminPermissions { get; set; }

    public virtual DbSet<Block> Blocks { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeRole> EmployeeRoles { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<TravelGroupsLog> TravelGroupsLogs { get; set; }

    public virtual DbSet<Expense> Expenses { get; set; }

    public virtual DbSet<ExpenseSplit> ExpenseSplits { get; set; }

    public virtual DbSet<ExternalLogin> ExternalLogins { get; set; }

    public virtual DbSet<Follow> Follows { get; set; }

    public virtual DbSet<ForumComment> ForumComments { get; set; }

    public virtual DbSet<ForumImage> ForumImages { get; set; }

    public virtual DbSet<ForumInteract> ForumInteracts { get; set; }

    public virtual DbSet<ForumPost> ForumPosts { get; set; }

    public virtual DbSet<FriendRequest> FriendRequests { get; set; }

    public virtual DbSet<Friendship> Friendships { get; set; }

    public virtual DbSet<GroupMember> GroupMembers { get; set; }

    public virtual DbSet<ItineraryNode> ItineraryNodes { get; set; }

    public virtual DbSet<JoinRequest> JoinRequests { get; set; }

    public virtual DbSet<LoginHistory> LoginHistories { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MemberSubscription> MemberSubscriptions { get; set; }

    public virtual DbSet<MemberToken> MemberTokens { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PostInteraction> PostInteractions { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }

    public virtual DbSet<TravelGroup> TravelGroups { get; set; }

    public virtual DbSet<VlogPost> VlogPosts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminAuditLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK_AdminAuditLogs");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Employee).WithMany(p => p.AdminAuditLogs)
                .HasConstraintName("FK_AdminAuditLogs_Employee");
        });

        modelBuilder.Entity<AdminLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__AdminLog__5E5499A8B71F8697");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Admin).WithMany(p => p.AdminLogs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AdminLogs__Admin__3493CFA7");
        });

        modelBuilder.Entity<AdminPermission>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Admin).WithMany(p => p.AdminPermissions).HasConstraintName("FK_AdminPermissions_Members");
        });

        modelBuilder.Entity<Block>(entity =>
        {
            entity.HasKey(e => new { e.BlockerId, e.BlockedId }).HasName("PK__Blocks__416BCA145ED007B7");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Blocked).WithMany(p => p.BlockBlockeds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Blocks__BlockedI__367C1819");

            entity.HasOne(d => d.Blocker).WithMany(p => p.BlockBlockers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Blocks__BlockerI__37703C52");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK_Employees");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue((byte)1);
        });

        modelBuilder.Entity<EmployeeRole>(entity =>
        {
            entity.HasKey(e => new { e.EmployeeId, e.RoleId }).HasName("PK_EmployeeRoles");

            entity.Property(e => e.GrantedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeRoles)
                .HasConstraintName("FK_EmployeeRoles_Employee");

            entity.HasOne(d => d.Role).WithMany(p => p.EmployeeRoles)
                .HasConstraintName("FK_EmployeeRoles_Role");
        });

        modelBuilder.Entity<Expense>(entity =>
        {
            entity.HasKey(e => e.ExpenseId).HasName("PK__Expenses__1445CFF3AEC30FE1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Group).WithMany(p => p.Expenses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Expenses__GroupI__3864608B");

            entity.HasOne(d => d.Payer).WithMany(p => p.Expenses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Expenses__PayerI__395884C4");
        });

        modelBuilder.Entity<ExpenseSplit>(entity =>
        {
            entity.HasKey(e => e.SplitId).HasName("PK__ExpenseS__06CEF2D3227BEDA1");

            entity.HasOne(d => d.Expense).WithMany(p => p.ExpenseSplits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExpenseSp__Expen__3A4CA8FD");

            entity.HasOne(d => d.Member).WithMany(p => p.ExpenseSplits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExpenseSp__Membe__3B40CD36");
        });

        modelBuilder.Entity<ExternalLogin>(entity =>
        {
            entity.HasKey(e => e.LoginId).HasName("PK__External__4DDA28384FBD7CAD");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithMany(p => p.ExternalLogins)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExternalL__Membe__3C34F16F");
        });

        modelBuilder.Entity<Follow>(entity =>
        {
            entity.HasKey(e => e.FollowId).HasName("PK__Follows__2CE8108E84365964");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue((byte)1);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Followee).WithMany(p => p.FollowFollowees)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Follows__Followe__3E1D39E1");

            entity.HasOne(d => d.Follower).WithMany(p => p.FollowFollowers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Follows__Followe__3D2915A8");
        });

        modelBuilder.Entity<ForumComment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__ForumCom__C3B4DFAA87459FFA");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.ForumPost).WithMany(p => p.ForumComments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ForumComm__Forum__3F115E1A");

            entity.HasOne(d => d.Member).WithMany(p => p.ForumComments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ForumComm__Membe__40058253");
        });

        modelBuilder.Entity<ForumImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__ForumIma__7516F4ECF9C4BC5A");

            entity.HasOne(d => d.ForumPost).WithMany(p => p.ForumImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ForumImag__Forum__40F9A68C");
        });

        modelBuilder.Entity<ForumInteract>(entity =>
        {
            entity.HasKey(e => new { e.ForumPostId, e.MemberId, e.ActionType }).HasName("PK__ForumInt__BE93040F60F2E848");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.ForumPost).WithMany(p => p.ForumInteracts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ForumInte__Forum__41EDCAC5");

            entity.HasOne(d => d.Member).WithMany(p => p.ForumInteracts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ForumInte__Membe__42E1EEFE");
        });

        modelBuilder.Entity<ForumPost>(entity =>
        {
            entity.HasKey(e => e.ForumPostId).HasName("PK__ForumPos__415AEB0CFEA90386");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithMany(p => p.ForumPosts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ForumPost__Membe__43D61337");
        });

        modelBuilder.Entity<FriendRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__FriendRe__33A8519A18ADD626");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Receiver).WithMany(p => p.FriendRequestReceivers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FriendReq__Recei__44CA3770");

            entity.HasOne(d => d.Requester).WithMany(p => p.FriendRequestRequesters)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FriendReq__Reque__45BE5BA9");
        });

        modelBuilder.Entity<Friendship>(entity =>
        {
            entity.HasKey(e => e.FriendshipId).HasName("PK__Friendsh__4D531A7459BD3BF4");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.MemberId1Navigation).WithMany(p => p.FriendshipMemberId1Navigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Friendshi__Membe__46B27FE2");

            entity.HasOne(d => d.MemberId2Navigation).WithMany(p => p.FriendshipMemberId2Navigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Friendshi__Membe__47A6A41B");
        });

        modelBuilder.Entity<GroupMember>(entity =>
        {
            entity.HasKey(e => e.GroupMemberId).HasName("PK__GroupMem__344812B2E81E1659");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.JoinedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Group).WithMany(p => p.GroupMembers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GroupMemb__Group__489AC854");

            entity.HasOne(d => d.Member).WithMany(p => p.GroupMemberMembers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GroupMemb__Membe__498EEC8D");

            entity.HasOne(d => d.RemovedByMember).WithMany(p => p.GroupMemberRemovedByMembers).HasConstraintName("FK__GroupMemb__Remov__4A8310C6");
        });

        modelBuilder.Entity<ItineraryNode>(entity =>
        {
            entity.HasKey(e => e.NodeId).HasName("PK__Itinerar__6BAE224383D52036");

            entity.HasOne(d => d.Post).WithMany(p => p.ItineraryNodes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Itinerary__PostI__4B7734FF");
        });

        modelBuilder.Entity<JoinRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__JoinRequ__33A8519AA98E2F9E");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Group).WithMany(p => p.JoinRequests)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__JoinReque__Group__4C6B5938");

            entity.HasOne(d => d.Member).WithMany(p => p.JoinRequestMembers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__JoinReque__Membe__4D5F7D71");

            entity.HasOne(d => d.ReviewedByMember).WithMany(p => p.JoinRequestReviewedByMembers).HasConstraintName("FK__JoinReque__Revie__4E53A1AA");
        });

        modelBuilder.Entity<LoginHistory>(entity =>
        {
            entity.Property(e => e.AttemptedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithMany(p => p.LoginHistories).HasConstraintName("FK_LoginHistories_Members");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK__Members__0CF04B383156A75F");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue((byte)1);
        });

        modelBuilder.Entity<MemberSubscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__MemberSu__9A2B24BD88FF083D");

            entity.HasOne(d => d.Member).WithMany(p => p.MemberSubscriptions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MemberSub__Membe__503BEA1C");

            entity.HasOne(d => d.Plan).WithMany(p => p.MemberSubscriptions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MemberSub__PlanI__51300E55");
        });

        modelBuilder.Entity<MemberToken>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("PK__MemberTo__658FEE8A58B57292");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithMany(p => p.MemberTokens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MemberTok__Membe__5224328E");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E320BDEFB19");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithMany(p => p.Notifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__Membe__531856C7");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK_Permissions");
        });

        modelBuilder.Entity<PostInteraction>(entity =>
        {
            entity.HasKey(e => new { e.PostId, e.MemberId, e.ActionType }).HasName("PK__PostInte__55DB8F3BB779147E");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Member).WithMany(p => p.PostInteractions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostInter__Membe__540C7B00");

            entity.HasOne(d => d.Post).WithMany(p => p.PostInteractions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostInter__PostI__55009F39");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Reports__D5BD48E5736AF2CA");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.ReportedMember).WithMany(p => p.ReportReportedMembers).HasConstraintName("FK__Reports__Reporte__56E8E7AB");

            entity.HasOne(d => d.Reporter).WithMany(p => p.ReportReporters)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reports__Reporte__55F4C372");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK_Roles");

            // Role.Permissions / Permission.Roles 多對多,共用既有的 RolePermissions 中介表
            // (RolePermission 實體本身保留,兩種存取方式並存)
            entity.HasMany(r => r.Permissions)
                .WithMany(p => p.Roles)
                .UsingEntity<RolePermission>(
                    right => right.HasOne(rp => rp.Permission).WithMany(p => p.RolePermissions),
                    left => left.HasOne(rp => rp.Role).WithMany(r => r.RolePermissions));
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => new { e.RoleId, e.PermissionId }).HasName("PK_RolePermissions");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions)
                .HasConstraintName("FK_RolePermissions_Role");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions)
                .HasConstraintName("FK_RolePermissions_Permission");
        });

        modelBuilder.Entity<SubscriptionPlan>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PK__Subscrip__755C22D7DDA444B6");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<TravelGroup>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__TravelGr__149AF30AF64F87EB");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CurrentPeople).HasDefaultValue(1);
            entity.Property(e => e.IsPublic).HasDefaultValue(true);
            entity.Property(e => e.JoinRule).HasDefaultValue((byte)1);
            entity.Property(e => e.MaxPeople).HasDefaultValue(10);
            entity.Property(e => e.MinPeople).HasDefaultValue(2);
            entity.Property(e => e.ReviewStatus)
                .HasDefaultValue("正常")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TravelGroups_ReviewStatus");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.OwnerMember).WithMany(p => p.TravelGroups)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TravelGro__Owner__57DD0BE4");
        });

        modelBuilder.Entity<TravelGroupsLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK_TravelGroupsLog");

            // 資料表名稱是單數 TravelGroupsLog,跟 DbSet 屬性名稱(複數)不一致,要明確指定
            entity.ToTable("TravelGroupsLog");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Group).WithMany(p => p.TravelGroupsLogs)
                .HasConstraintName("FK_TravelGroupsLog_Group");

            entity.HasOne(d => d.ChangedByEmployee).WithMany(p => p.TravelGroupsLogs)
                .HasConstraintName("FK_TravelGroupsLog_ChangeByEmployee");
        });

        modelBuilder.Entity<VlogPost>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__VlogPost__AA126038E4AC2808");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TravelDays).HasDefaultValue(1);

            entity.HasOne(d => d.Member).WithMany(p => p.VlogPosts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VlogPosts__Membe__58D1301D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
