// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class LoginHistory
{
    public int HistoryId { get; set; }

    public int MemberId { get; set; }

    public string LoginIp { get; set; }

    public bool IsSuccess { get; set; }

    public string UserAgent { get; set; }

    public DateTime AttemptedAt { get; set; }

    public virtual Member Member { get; set; }
}