// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

[Index("Email", Name = "UQ__Members__A9D105345A0A7EED", IsUnique = true)]
public partial class Member
{
    [Key]
    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(255)]
    public string PasswordHash { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(50)]
    public string LineId { get; set; }

    public bool IsPrivateAccount { get; set; }

    public bool IsEmailConfirmed { get; set; }

    public string AvatarUrl { get; set; }

    public DateOnly? BirthDate { get; set; }

    public byte Gender { get; set; }

    [StringLength(50)]
    public string Occupation { get; set; }

    [Column("MBTI")]
    [StringLength(4)]
    [Unicode(false)]
    public string Mbti { get; set; }

    [StringLength(500)]
    public string Bio { get; set; }

    public byte Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [StringLength(255)]
    public string InstagramUrl { get; set; }

    [StringLength(255)]
    public string FacebookUrl { get; set; }

    public byte ContactBookVisibility { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLoginAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastLoginIp { get; set; }

    public int FailedLoginCount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LockoutEndDate { get; set; }

    [InverseProperty("Admin")]
    public virtual ICollection<AdminLog> AdminLogs { get; set; } = new List<AdminLog>();

    [InverseProperty("Admin")]
    public virtual ICollection<AdminPermission> AdminPermissions { get; set; } = new List<AdminPermission>();

    [InverseProperty("Blocked")]
    public virtual ICollection<Block> BlockBlockeds { get; set; } = new List<Block>();

    [InverseProperty("Blocker")]
    public virtual ICollection<Block> BlockBlockers { get; set; } = new List<Block>();

    [InverseProperty("Member")]
    public virtual ICollection<ExpenseSplit> ExpenseSplits { get; set; } = new List<ExpenseSplit>();

    [InverseProperty("Payer")]
    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    [InverseProperty("Member")]
    public virtual ICollection<ExternalLogin> ExternalLogins { get; set; } = new List<ExternalLogin>();

    [InverseProperty("Followee")]
    public virtual ICollection<Follow> FollowFollowees { get; set; } = new List<Follow>();

    [InverseProperty("Follower")]
    public virtual ICollection<Follow> FollowFollowers { get; set; } = new List<Follow>();

    [InverseProperty("Member")]
    public virtual ICollection<ForumComment> ForumComments { get; set; } = new List<ForumComment>();

    [InverseProperty("Member")]
    public virtual ICollection<ForumInteract> ForumInteracts { get; set; } = new List<ForumInteract>();

    [InverseProperty("Member")]
    public virtual ICollection<ForumPost> ForumPosts { get; set; } = new List<ForumPost>();

    [InverseProperty("Receiver")]
    public virtual ICollection<FriendRequest> FriendRequestReceivers { get; set; } = new List<FriendRequest>();

    [InverseProperty("Requester")]
    public virtual ICollection<FriendRequest> FriendRequestRequesters { get; set; } = new List<FriendRequest>();

    [InverseProperty("MemberId1Navigation")]
    public virtual ICollection<Friendship> FriendshipMemberId1Navigations { get; set; } = new List<Friendship>();

    [InverseProperty("MemberId2Navigation")]
    public virtual ICollection<Friendship> FriendshipMemberId2Navigations { get; set; } = new List<Friendship>();

    [InverseProperty("Member")]
    public virtual ICollection<GroupMember> GroupMemberMembers { get; set; } = new List<GroupMember>();

    [InverseProperty("RemovedByMember")]
    public virtual ICollection<GroupMember> GroupMemberRemovedByMembers { get; set; } = new List<GroupMember>();

    [InverseProperty("Member")]
    public virtual ICollection<JoinRequest> JoinRequestMembers { get; set; } = new List<JoinRequest>();

    [InverseProperty("ReviewedByMember")]
    public virtual ICollection<JoinRequest> JoinRequestReviewedByMembers { get; set; } = new List<JoinRequest>();

    [InverseProperty("Member")]
    public virtual ICollection<LoginHistory> LoginHistories { get; set; } = new List<LoginHistory>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberSubscription> MemberSubscriptions { get; set; } = new List<MemberSubscription>();

    [InverseProperty("Member")]
    public virtual ICollection<MemberToken> MemberTokens { get; set; } = new List<MemberToken>();

    [InverseProperty("Member")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("Member")]
    public virtual ICollection<PostInteraction> PostInteractions { get; set; } = new List<PostInteraction>();

    [InverseProperty("ReportedMember")]
    public virtual ICollection<Report> ReportReportedMembers { get; set; } = new List<Report>();

    [InverseProperty("Reporter")]
    public virtual ICollection<Report> ReportReporters { get; set; } = new List<Report>();

    [InverseProperty("OwnerMember")]
    public virtual ICollection<TravelGroup> TravelGroups { get; set; } = new List<TravelGroup>();

    [InverseProperty("ChangedByMember")]
    public virtual ICollection<TravelGroupsLog> TravelGroupsLogs { get; set; } = new List<TravelGroupsLog>();

    [InverseProperty("Member")]
    public virtual ICollection<VlogPost> VlogPosts { get; set; } = new List<VlogPost>();
}