// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class MemberSubscription
{
    public int SubscriptionId { get; set; }

    public int MemberId { get; set; }

    public int PlanId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int Status { get; set; }

    public virtual Member Member { get; set; }

    public virtual SubscriptionPlan Plan { get; set; }
}