// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// 🌟 手動加了 IdentityUser<int> 繼承，並移除掉反向工程重新產生、跟 IdentityUser 內建屬性
// 重複的 14 個欄位（Id/UserName/NormalizedUserName/Email/NormalizedEmail/EmailConfirmed/
// PasswordHash/SecurityStamp/ConcurrencyStamp/PhoneNumber/PhoneNumberConfirmed/
// TwoFactorEnabled/LockoutEnd/LockoutEnabled/AccessFailedCount），改由基底類別提供。
// 每次重新反向工程都會被蓋回純 POCO class，記得要改回來。
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace LazyTravel.Shared.Models.EfModels;

public partial class Member : IdentityUser<int>
{
    public string Name { get; set; }

    public string LineId { get; set; }

    public string InstagramUrl { get; set; }

    public string FacebookUrl { get; set; }

    public byte ContactBookVisibility { get; set; }

    public bool IsPrivateAccount { get; set; }

    public string AvatarUrl { get; set; }

    public DateOnly? BirthDate { get; set; }

    public byte Gender { get; set; }

    public string Occupation { get; set; }

    public string Mbti { get; set; }

    public string Bio { get; set; }

    public byte Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public string LastLoginIp { get; set; }

    public bool IsDelete { get; set; }

    public string City { get; set; }

    public virtual ICollection<Block> BlockBlockeds { get; set; } = new List<Block>();

    public virtual ICollection<Block> BlockBlockers { get; set; } = new List<Block>();

    public virtual ICollection<ExpenseSplit> ExpenseSplits { get; set; } = new List<ExpenseSplit>();

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<Follow> FollowFollowees { get; set; } = new List<Follow>();

    public virtual ICollection<Follow> FollowFollowers { get; set; } = new List<Follow>();

    public virtual ICollection<FriendRequest> FriendRequestReceivers { get; set; } = new List<FriendRequest>();

    public virtual ICollection<FriendRequest> FriendRequestRequesters { get; set; } = new List<FriendRequest>();

    public virtual ICollection<Friendship> FriendshipMemberId1Navigations { get; set; } = new List<Friendship>();

    public virtual ICollection<Friendship> FriendshipMemberId2Navigations { get; set; } = new List<Friendship>();

    public virtual ICollection<GroupMember> GroupMemberMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<GroupMember> GroupMemberRemovedByMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<JoinRequest> JoinRequestMembers { get; set; } = new List<JoinRequest>();

    public virtual ICollection<JoinRequest> JoinRequestReviewedByMembers { get; set; } = new List<JoinRequest>();

    public virtual ICollection<LoginHistory> LoginHistories { get; set; } = new List<LoginHistory>();

    public virtual ICollection<MemberClaim> MemberClaims { get; set; } = new List<MemberClaim>();

    public virtual ICollection<MemberLogin> MemberLogins { get; set; } = new List<MemberLogin>();

    public virtual ICollection<MemberSkill> MemberSkills { get; set; } = new List<MemberSkill>();

    public virtual ICollection<MemberSubscription> MemberSubscriptions { get; set; } = new List<MemberSubscription>();

    public virtual ICollection<MemberToken> MemberTokens { get; set; } = new List<MemberToken>();

    public virtual ICollection<MemberTravelDNA> MemberTravelDnas { get; set; } = new List<MemberTravelDNA>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<PostInteraction> PostInteractions { get; set; } = new List<PostInteraction>();

    public virtual ICollection<Report> ReportReportedMembers { get; set; } = new List<Report>();

    public virtual ICollection<Report> ReportReporters { get; set; } = new List<Report>();

    public virtual ICollection<TravelGroupImage> TravelGroupImages { get; set; } = new List<TravelGroupImage>();

    public virtual ICollection<TravelGroupInteraction> TravelGroupInteractions { get; set; } = new List<TravelGroupInteraction>();

    public virtual ICollection<TravelGroup> TravelGroups { get; set; } = new List<TravelGroup>();

    public virtual ICollection<VlogPostImage> VlogPostImages { get; set; } = new List<VlogPostImage>();

    public virtual ICollection<VlogPost> VlogPosts { get; set; } = new List<VlogPost>();

    public virtual ICollection<MemberRole> Roles { get; set; } = new List<MemberRole>();
}