// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class MemberRole
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string NormalizedName { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual ICollection<MemberRoleClaim> MemberRoleClaims { get; set; } = new List<MemberRoleClaim>();

    public virtual ICollection<Member> Users { get; set; } = new List<Member>();
}