// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class MemberSubscription
{
    [Key]
    [Column("SubscriptionID")]
    public int SubscriptionId { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    [Column("PlanID")]
    public int PlanId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    public int Status { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("MemberSubscriptions")]
    public virtual Member Member { get; set; }

    [ForeignKey("PlanId")]
    [InverseProperty("MemberSubscriptions")]
    public virtual SubscriptionPlan Plan { get; set; }
}