// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

[Index("PermissionCode", Name = "UQ_Permissions_PermissionCode", IsUnique = true)]
public partial class Permission
{
    [Key]
    [Column("PermissionID")]
    public int PermissionId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string PermissionCode { get; set; }

    [Required]
    [StringLength(50)]
    public string ModuleName { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [InverseProperty("Permission")]
    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();

    // Role.Permissions 的反向端,見 LazyTravelDBContext 的 UsingEntity<RolePermission>
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}
