// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

[Index("PermissionCode", Name = "UQ__Permissi__91FE575053D3551D", IsUnique = true)]
public partial class Permission
{
    [Key]
    [Column("PermissionID")]
    public int PermissionId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string PermissionCode { get; set; }

    [Required]
    [StringLength(50)]
    public string ModuleName { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [ForeignKey("PermissionId")]
    [InverseProperty("Permissions")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}