// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

[PrimaryKey("PostId", "MemberId", "ActionType")]
public partial class PostInteraction
{
    [Key]
    [Column("PostID")]
    public int PostId { get; set; }

    [Key]
    [Column("MemberID")]
    public int MemberId { get; set; }

    [Key]
    public byte ActionType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("PostInteractions")]
    public virtual Member Member { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("PostInteractions")]
    public virtual VlogPost Post { get; set; }
}