// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

// 官方 9 欄 + 本機額外 ALTER TABLE 加的 5 欄(ReasonCategory/IsMalicious/TargetTitle/Description/EvidenceUrl),
// 詳細欄位定義見 Desktop/補上檢舉審核台Reports欄位.sql
public partial class Report
{
    [Key]
    [Column("ReportID")]
    public int ReportId { get; set; }

    [Column("ReporterID")]
    public int ReporterId { get; set; }

    [Column("ReportedMemberID")]
    public int? ReportedMemberId { get; set; }

    public byte ReportType { get; set; }

    [Column("TargetID")]
    public int? TargetId { get; set; }

    [Required]
    [StringLength(500)]
    public string Reason { get; set; }

    public byte ReportStatus { get; set; }

    [StringLength(500)]
    public string AdminNotes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    public byte ReasonCategory { get; set; }

    public bool IsMalicious { get; set; }

    [StringLength(200)]
    public string TargetTitle { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [StringLength(300)]
    public string EvidenceUrl { get; set; }

    [ForeignKey("ReportedMemberId")]
    [InverseProperty("ReportReportedMembers")]
    public virtual Member ReportedMember { get; set; }

    [ForeignKey("ReporterId")]
    [InverseProperty("ReportReporters")]
    public virtual Member Reporter { get; set; }
}
