// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class ReportReasonCategoryLookup
{
    public byte CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
}