// <auto-generated> This file has been generated via `dotnet ef dbcontext scaffold` (table: ReportReasonCategories). </auto-generated>
namespace LazyTravel.Models.EfModels;

public partial class ReportReasonCategoryLookup
{
    public byte CategoryId { get; set; }

    public string CategoryName { get; set; } = null!;
}
