// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// 🌟 這張表是手動新增的（沒有跑反向工程），對應資料庫新增的 TravelGroupInteractions 表。
// ActionType 型別跟 PostInteraction.cs 一樣，如果之後真的重新反向工程覆蓋了這個檔案，
// 記得要把 ActionType 改回 TravelGroupInteractionType（見 TravelGroupInteractionEnums.cs）。
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelGroupInteraction
{
    public int GroupId { get; set; }

    public int MemberId { get; set; }

    public TravelGroupInteractionType ActionType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TravelGroup Group { get; set; }

    public virtual Member Member { get; set; }
}
