// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelGroupItineraryItem
{
    public int ItineraryItemId { get; set; }

    public int GroupId { get; set; }

    public int DayNumber { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string Title { get; set; }

    public string LocationName { get; set; }

    public string Description { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual TravelGroup Group { get; set; }
}