// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelSkill
{
    public int SkillId { get; set; }

    public string SkillName { get; set; }

    public byte SkillCategory { get; set; }

    public string IconCode { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<MemberSkill> MemberSkills { get; set; } = new List<MemberSkill>();
}