// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class TravelGroupsLog
{
    public int LogId { get; set; }

    public int GroupId { get; set; }

    public int ChangeByMemberId { get; set; }

    public string FieldName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string ChangeType { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Remark { get; set; }

    public virtual Employee ChangeByMember { get; set; }

    public virtual TravelGroup Group { get; set; }
}