// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class VlogPostImage
{
    public int ImageId { get; set; }

    public int VlogPostId { get; set; }

    public string ImageUrl { get; set; }

    public byte ImageType { get; set; }

    public string AltText { get; set; }

    public int SortOrder { get; set; }

    public bool IsCover { get; set; }

    public bool IsDeleted { get; set; }

    public int? UploadedByMemberId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Member UploadedByMember { get; set; }

    public virtual VlogPost VlogPost { get; set; }
}