// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LazyTravel.Models.EfModels;

public partial class VlogPost
{
    [Key]
    [Column("PostID")]
    public int PostId { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(150)]
    public string Title { get; set; }

    [StringLength(500)]
    public string MediaUrl { get; set; }

    public byte MediaType { get; set; }

    public string Content { get; set; }

    [Required]
    [StringLength(100)]
    public string Destination { get; set; }

    public int TravelDays { get; set; }

    public byte Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public bool IsDelete { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<ItineraryNode> ItineraryNodes { get; set; } = new List<ItineraryNode>();

    [ForeignKey("MemberId")]
    [InverseProperty("VlogPosts")]
    public virtual Member Member { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<PostInteraction> PostInteractions { get; set; } = new List<PostInteraction>();
}