// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LazyTravel.Shared.Models.EfModels;

public partial class VlogPost
{
    public int PostId { get; set; }

    public int MemberId { get; set; }

    public string Title { get; set; }

    public string MediaUrl { get; set; }

    public VlogMediaType MediaType { get; set; }

    public string Content { get; set; }

    public string Destination { get; set; }

    public int TravelDays { get; set; }

    public VlogPostStatus Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? TravelDate { get; set; }

    public TravelGroupSize TravelPeople { get; set; }

    public bool IsDelete { get; set; }

    public virtual ICollection<ItineraryNode> ItineraryNodes { get; set; } = new List<ItineraryNode>();

    public virtual Member Member { get; set; }

    public virtual ICollection<PostInteraction> PostInteractions { get; set; } = new List<PostInteraction>();

    public virtual ICollection<VlogPostImage> VlogPostImages { get; set; } = new List<VlogPostImage>();

    public virtual ICollection<VlogPostTag> VlogPostTags { get; set; } = new List<VlogPostTag>();
}